### ISSUE TITLE
Add a configurable glowing effect?

### ISSUE THREAD

**Issue by ConV2014** [ps-dps/MobCaptains#1]
It would be nice to have a toggleable glowing effect for mob captains to make them easier to find. Even with my spawn rate up, I've only actually found a mob captain once or twice after the message appeared.

**Comment by benio1394** [comment]
I like this idea, that should be a feature

**Comment by PuckiSilver** [comment]
Hey, the option to make Mob Captains have the glowing effect was added in the just now released [version 2.1.2](https://modrinth.com/datapack/mob-captains/version/v2.1.2)
