### ISSUE TITLE
Change the sound or make it disable-able?

### ISSUE THREAD

**Issue by alexmshepherd** [ps-dps/MobCaptains#10]
The spawn sound gives me a heart attack every twenty minutes or so.

**Comment by PuckiSilver** [comment]
I will close this for now, if you still need help with this or it is an actual feature request - feel free to comment in this issue or formulate a new issue

**Comment by alexmshepherd** [comment]
Yes, I want to be able to disable the sound independently.

**Comment by PuckiSilver** [comment]
The config option has been added in the just now released [version 2.1.1](https://modrinth.com/datapack/mob-captains/version/v2.1.1)
