### ISSUE TITLE
Glow effect not shown?

### ISSUE THREAD

**Issue by Faivonisme** [ps-dps/MobCaptains#14]
The issue is sometime it shown sometime it's not. 
Also I'd like to file some concerns : 
- The particle beam is too short (can't be seen from indoor or inside cave), there should be a configuration whether how long it should stay and/or the color of the beam
- Configurable how far the mob captain can spawn from the player. Sometimes it spawn far far far down the cave (even tho glow effect is enabled sometimes it's not shown)
- About the glow effect, maybe can be setup to always shown whether behind the blocks or not. 

It's really fun hunting the mob captains but finding them is so painful, with the glow effect and particle beam not really helping they despawn faster than anything. Hope to see this mod becomes viral~

**Comment by PuckiSilver** [comment]
The glowing effect is visible through blocks by default.
I can't make the particle beam stay longer, that's a limitation of minecraft commands.
The spawn distance of Mob Captains to players will be configurable in v3.0.0, the next release! 🎉
