### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by Miraknuqzir23** [ps-dps/MobCaptains#15]
Hi I'm Mirak. 
About Mob Captain Spawn, how do i set the spawn distance so they don't spawn underground but on the surface?
1 more, how to manage their number to spawn?

That's all, thankyou!!

**Comment by PuckiSilver** [comment]
You can't yet determine how much they should spawn on the surface or in caves, that feature is planned.

To configure how many spawn, you can run `/function ps-mob:config` in chat.
In the menu you can then lower the cool down or increase the spawn change to increase how many MobCaptains spawn.

**Comment by Miraknuqzir23** [comment]
It was very helpful, thanks FYI!

Pada tanggal Kam, 15 Jun 2023 pukul 13.03 PuckiSilver <
***@***.***> menulis:
