### ISSUE TITLE
Unable to work out how to change options

### ISSUE THREAD

**Issue by WnndGws** [ps-dps/MobCaptains#17]
Can you please put an example in the README? I have tried to Google to no avail, Thanks!!

**Comment by WnndGws** [comment]
I can see it, but then how do I change it? Apologies if I'm missing something obvious

**Comment by PuckiSilver** [comment]
Open the chat and click on the setting with your mouse, then it should put a command in your chat area.

There you can add the number you want to set it to and then you just sent the command.

**Comment by WnndGws** [comment]
OHHH, thanks!!! Thats the bit I didn't know! Thanks!

**Comment by nxysjay** [comment]
im trying to click on the options in chat and its not working
