### ISSUE TITLE
I turned into a Mob Captain

### ISSUE THREAD

**Issue by KhosuDeimos** [ps-dps/MobCaptains#18]
I used the command /function ps-mob:convert/legendary

Now i dont know how to remove it from me

I did: 
/effect clear @a
/kill @a

pls help me remove the effects i have a bunch of heart and speed idk how to remove it

**Comment by PuckiSilver** [comment]
At the bottom of [this issue](https://github.com/ps-dps/MobCaptains/issues/5) I explained the commands to remove all the effects
You can also just remove the tags and go through an end portal to the overworld (this is abusing a bug that removed all attribute modifiers in vanilla minecraft)

**Comment by KhosuDeimos** [comment]
Thank you ur datapack is cool btw <3
