### ISSUE TITLE
How to change settings like spawnrate?

### ISSUE THREAD

**Issue by auroraongithub** [ps-dps/MobCaptains#2]
hi, i run my server on revivenode, but i'm not sure where to find the files to change the settings of the datapack. thanks.

**Comment by PuckiSilver** [comment]
Hey,
sorry for not coming back to you sooner, this issue got burried.

Version v2.1.0 of MobCaptains introduces a function that can be called ingame by anyone with OP permissions.
Said function opens a configuration menu in chat, that should make it a lot more accessible to modify how the data pack is configured!

The update is available to [download on Modrinth](https://modrinth.com/datapack/mob-captains/versions) right now
~PuckiSilver

**Comment by auroraongithub** [comment]
thank you!
