### ISSUE TITLE
Unknown Scoreboard Objective 'ps-mob:config'

### ISSUE THREAD

**Issue by EvanoriMemoria** [ps-dps/MobCaptains#20]
Minecraft 1.19.2 Reincarnation Modpack

When using the `/function ps-mob:config` command and clicking on the settings, I get the error `Unknown Scoreboard Objective 'ps-mob:config'`. 

I've attempted to use both the datapack and the mod. Autofill works but the scoreboard doesn't seem to be getting initialized. I'm not incredibly familiar with scoreboards, any insights you can provide me?

**Comment by PuckiSilver** [comment]
The scoreboard should be called `ps-mob.config` and it is initialized when reloading, joining the world or restarting the server.
I haven't yet heard of such error nor can I replicate it myself so I assume it's the modpack messing with vanilla data pack behavior.
Are you getting the same error in a fully vanilla setting (no mods/plugins/data packs, just this pack)?

**Comment by EvanoriMemoria** [comment]
Ah, that was a typo on my end, it is indeed `Unknown Scoreboard Objective 'ps-mob.config'`

Fully vanilla it does work as intended, I was hoping you may have come across mods that mess with data pack/scoreboard behavior in this way before, but it sounds unlikely. I would love to track down the culprit.

Thank you for your reply. I greatly appreciate it.

**Comment by PuckiSilver** [comment]
If you find the mod causing this please do let me know so I can warn people about it or even fix that incompatibility on my end.

**Comment by EvanoriMemoria** [comment]
> If you find the mod causing this please do let me know so I can warn people about it or even fix that incompatibility on my end.

Adapted Origins https://modrinth.com/mod/adapted-origins/versions was the culprit. Seems it goes way beyond it's scope. It was breaking a lot more than just your mod turns out, just a warning would likely be good for this one.
