### ISSUE TITLE
Command config stopped working.

### ISSUE THREAD

**Issue by ztede** [ps-dps/MobCaptains#22]
Hello, I've been using (and enjoying) your datapacks/mods in my server, however the commands for config has suddenly stopped working. I am able to pull up the config menu in chat but unable to change any of setting. Every time I try to change, it results in "unknown scoreboard objective". Do you have any troubleshoot for this issue? It occurs in Keep Some Inventory mod also. I am using the mod version.

-Update-
Fixed it by changing to datapack version.

**Comment by PuckiSilver** [comment]
Hm, strange that it would suddenly stop working, glad you figured out a workaround though
