### ISSUE TITLE
400% increase in bandwith usage

### ISSUE THREAD

**Issue by oslavq** [ps-dps/MobCaptains#23]
I have installed Mob Captains mod on my Minecraft server, and suddenly bandwidth usage increased by 400% when player is still and not loading chunks or moving, here is a screenshot of the upload rate with mod installed on server:
![Screenshot_20231028_215311](https://github.com/ps-dps/MobCaptains/assets/133600024/fbbf7420-d327-49c3-9cdf-4425f158a721)

without the mod:
![Screenshot_20231028_221528](https://github.com/ps-dps/MobCaptains/assets/133600024/073cf11d-c7be-4181-a6d4-869173f4f34f)

The player was not moving and was in the exact same position during the tests, screenshots of bandwidth were taken after chunks were loaded

**Mods installed on my server**
`├── Amplified_Nether_1.19.3_v1.2.1.jar
├── anti-xray-1.3.0-Fabric-1.19.2.jar
├── appliedenergistics2-fabric-12.9.8.jar
├── audaki_cart_engine--fabric-mc1.19.4--v2.0.3.jar
├── betterbeaconplacement-1.19.2-3.1.jar
├── betterthanmending-1.3.0.jar
├── bigger_end_cities-1.19.3-1.0.0.jar
├── boat-step-up-1.2.2+1.19.jar
├── c2me-fabric-mc1.19.2-0.2.0+alpha.9.11.jar
├── chunksending-fabric-1.19.2-2.6.jar
├── Chunky-1.3.38.jar
├── collective-1.19.2-6.65.jar
├── create_enchantment_industry-1.0.1.b.jar
├── create-fabric-0.5.1-c-build.1160+mc1.19.2.jar
├── create_jetpack-fabric-3.3.1.jar
├── create-track-map-1.4+mc1.19.2-fabric-create-0.5.1.jar
├── cupboard-fabric-1.19.2-2.0.jar
├── DailyDad-Server-fabric-1.19-1.3.3.jar
├── EmeraldTools-Fabric-1.19.2-1.4.38.jar
├── endermanoverhaul-fabric-1.19.2-0.0.0.jar
├── endgame-reborn-1.19-v1.0.5.jar
├── endium-v2.0.0-beta_1.jar
├── expandedstorage-8.3.4+1.19.2-fabric.jar
├── ExtendedDrawers-1.4.5+mc.1.19.2.jar
├── fabric-api-0.76.1+1.19.2.jar
├── fabric-carpet-1.19.2-1.4.84+v221018.jar
├── fabric-end-remastered-5.2.0-1.19.2.jar
├── fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
├── FabricShieldLib-1.7-1.19.2.jar
├── fabrictailor-2.0.1.jar
├── ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
├── geckolib-fabric-1.19-3.1.40.jar
├── gottagofast-1.0.2-1.19.2.jar
├── jei-1.19.2-fabric-11.6.0.1018.jar
├── journeymap-1.19.2-5.9.7-fabric.jar
├── jsst-1.19-0.1.4.jar
├── LeavesBeGone-v4.0.1-1.19.2-Fabric.jar
├── lithium-fabric-mc1.19.2-0.11.1.jar
├── MapFrontiers-1.19.2-2.5.1-fabric.jar
├── memoryleakfix-fabric-1.17+-1.1.2.jar
├── mes-1.2-1.19.2-fabric.jar
├── moonlight-1.19.2-2.2.45-fabric.jar
├── plenty-of-armors-1.3.0+mc1.19.2.jar
├── polymorph-fabric-0.46.4+1.19.2.jar
├── PuzzlesLib-v4.4.3-1.19.2-Fabric.jar
├── resourcefulconfig-fabric-1.19.2-1.0.20.jar
├── resourcefullib-fabric-1.19.2-1.1.24.jar
├── serversleep-datapack.jar
├── servertick-mc1.19-1.7.jar
├── spark-1.10.37-fabric.jar
├── starlight-1.1.1+fabric.ae22326.jar
├── Steam_Rails-1.5.1+fabric-mc1.19.2.jar
├── supplementaries-1.19.2-2.3.24-fabric.jar
├── Technical- Enchant+_v1.0.2_1.19.2_Fabric.jar
├── Terralith_1.19.3_v2.3.11.jar
├── toms_storage_fabric-1.19-1.5.9.jar
├── TooManyTools1.0.jar
├── ultris-5.6.7g.jar
├── uncraftables+-1.1.jar
├── vanilla-refresh-1.4.17.jar
├── viewdistancefix-1.19.2-1.0.0.jar
└── wraith-silkspawners-1.1.2.jar`

**Server launch command:**
java -Xmx3G -jar fabric-server-mc.1.19.2-loader.0.14.22-launcher.0.11.2.jar nogui

The host machine is Linux 64 bit with JDK 21 installed on it
I also tried removing all of the mods and leaving only Mob Captains mod but get same exact issue
Server is 1.19.2 fabric 0.14.22
What might be causing the issue? It is a real problem on limited connections, especially when a lot of players are on the server

**Comment by oslavq** [comment]
UPD: mod version is `mob-captains-v2.1.2`

**Comment by PuckiSilver** [comment]
Hey,
The mod is just a data pack packaged as a mod, it doesn’t contain any java classes.
Since data packs don’t have the ability to send packets or other traffic directly, I don’t know how MobCaptains can be at fault but maybe I'm missing something.

A reason more packets could be sent may be the particles spawning at MobCaptains, but I can’t imagine that increasing upload by 162% like shown in the pictures.
