### ISSUE TITLE
Spawn a captain manually

### ISSUE THREAD

**Issue by Cosmeak** [ps-dps/MobCaptains#25]
I add to the loot table an item and want to test it, but can't find any command to summon a captain, did the datapack have one ?

And i accidentally transform myself has a captain and can't remove it, did you have any idea on how to remove on myself ?

PS: your datapack is so cool, everyone on our server love it. Thank you for it

**Comment by PuckiSilver** [comment]
Hey!

You can’t directly spawn them, you rather convert a mob to a captain. To convert a zombie into a legendary mob captain, run the following command while standing next to it:
```mcfunction
execute as @e[​type=zombie,limit=1,sort=nearest] run function ps-mob:convert/legendary
```
> You can change the type and rarity to your needs

In [this issue](https://github.com/ps-dps/MobCaptains/issues/5) are commands to un-MobCaptainify yourself

Thank you! Glad you and your friends are enjoying the pack :D

**Comment by Cosmeak** [comment]
Thank you so much for your quick answer, that exactly what we wanted!
