### ISSUE TITLE
config function does not exist (1.20.4)

### ISSUE THREAD

**Issue by LoveToHateYou** [ps-dps/MobCaptains#29]
sorry if this is stupid, but for some reason I can't use the config command to change the settings for the datapack, all the other functions are visible, but '/function ps-mob:config' doesn't work and I get 'Unknown function ps-mob:config'

**Comment by PuckiSilver** [comment]
Strange, do you have any other mods installed? Did you try rejoining the world/restarting the server or running /reload?

**Comment by LoveToHateYou** [comment]
I'm using the datapack version as, no other mods or datapacks installed aside from performance mods and the ones people use like AppleSkin, 3d-Skin-Layers, BetterF3, etc...

short video: https://youtu.be/aahQ_1H-yOY

I can still use the scoreboard commands to change stuff, but the function command doesn't work

also another thing, how rare are the drops from mobs? I was testing with increased spawn rate for the captains in creative and after constant killing for like 2 hours I was not able to get a drop

I want to be able to use this in a realm with friends

**Comment by PuckiSilver** [comment]
That is indeed strange, I'll look into it, maybe something in 1.20.4 did break the data pack.

The mobs should also drop a piece of gear every time you kill them, so that seems to also be bugged.

Only thing you can try - would be in fully vanilla but it doesn't look like it would change that.

I will update the mod for the newest versions when I get the time, sorry for the inconvenience!

**Comment by setzke** [comment]
I'm in full vanilla (1.20.4) with some datapacks and I noticed there's no config.
My issue may be different, though -- I've noticed no activation of the datapack, yet. Figured I'd fiddle with config to try to activate it.
![image](https://github.com/ps-dps/MobCaptains/assets/13110348/4a03f5c6-96f8-4c04-866d-b06603557d0d)
![image](https://github.com/ps-dps/MobCaptains/assets/13110348/c6eb0cfe-4ae7-4523-94e1-6a0b5ac81e6c)
![image](https://github.com/ps-dps/MobCaptains/assets/13110348/80286c45-5164-43f6-95a5-8c0cb55282ed)

**Comment by setzke** [comment]
One of my worlds did work so I'm a bit baffled. Too lazy to go back into that one right now (sorry!)
I will offer, this, though. I deactivated all resource packs, loaded only MobCaptains datapack (Modrinth), and created a new world in Vanilla 1.20.4. Here's the log:
https://pastebin.com/9uFbnrEU

![image](https://github.com/ps-dps/MobCaptains/assets/13110348/7381db70-38e4-4b0f-9b0f-d2cf4bcca50a)

**Comment by setzke** [comment]
Fix for loot tables is to remove the "quotation marks" from every instance of "true" and "false"
![image](https://github.com/ps-dps/MobCaptains/assets/13110348/c483f0e3-595e-4c38-badc-3bb16545fce4)

**Comment by setzke** [comment]
Fixed the config -- you have "suggest_legendary" instead of "suggest_command".
I don't know JSON, so I was butchering this document up down left and right, only to stumble onto this "oh duh" error towards the end. 😅

**Comment by PuckiSilver** [comment]
This all should be fixed in v3.1.0, thank y'all for pointing out the errors
https://modrinth.com/datapack/mob-captains/version/v3.1.0
