### ISSUE TITLE
Unknown Scoreboard

### ISSUE THREAD

**Issue by Jeavess** [ps-dps/MobCaptains#32]
For some reason when im trying to configure rhe scores it says unknown scoreboard something… pls help it worked perfectly on my other server

**Comment by PuckiSilver** [comment]
Please provide more information, just "it doesn’t work but it did before" isn’t enough for me to tell you anything!

Where is the data pack installed right now? Singleplayer? Multiplayer?

What server software/mods are you using alongside the pack?

Are you using the data pack or the mod version?

Does the data pack show up when running `/datapack list`?

If anything else is any different from just vanilla minecraft in the correct version and the pack - please tell me, if I don’t know what your setup is, I won’t be able to determine what’s broken..

**Comment by Jeavess** [comment]
I am running the datapack version 3.1.1 nothing in the plugins is conficting with other plugins.
runnen 1.20.1 paper server

![image](https://github.com/ps-dps/MobCaptains/assets/63520533/34bb0bc4-454b-4a40-abaa-486625eac3ce)
![image](https://github.com/ps-dps/MobCaptains/assets/63520533/a254e22c-46b4-4da5-8bcb-b31007151918)

**Comment by PuckiSilver** [comment]
PaperMC breaks a lot of vanilla features that data packs require to function.
There may not be a way to fix this.

**Comment by Jeavess** [comment]
okay weird because it worked before the wipe of my server and still on the same version

**Comment by PuckiSilver** [comment]
Paper provides settings to re-enable these missing features - did you mess with any of those?

**Comment by Jeavess** [comment]
nope i  did not mess with any settings u just wiped the server

**Comment by Jeavess** [comment]
maybe the load order of the datapacks?

**Comment by PuckiSilver** [comment]
try running `/reload` or `/function #minecraft:load`, maybe the load function didn't run?

**Comment by Jeavess** [comment]
how do force load the datapack?

**Comment by PuckiSilver** [comment]
This is stale - I don’t think I can help with PaperMC, there are way too many problems relating to it.
