### ISSUE TITLE
Config keeps resetting itself, sometimes during the same session that I changed it during.

### ISSUE THREAD

**Issue by Barerock** [ps-dps/MobCaptains#35]
Really not much to describe. After around 250 days of the config being obeyed, it now resets itself randomly. There's no config file to set to read-only, unfortunately, but I see you're working on something for that.

**Comment by PuckiSilver** [comment]
What server software and/or other mods/plugins/data packs are you using?

That should never happen and I have yet to hear reports about that 🤔

**Comment by Barerock** [comment]
Sorry, I didn't get a notification. My email signed out.

I am using quite a few mods, and I don't think it's reset itself for a while, but I also haven't played too much recently. I have swapped between Configured and Forge Config Screens a couple times to fix some things, but it's been a while since that occurred. This is in Singleplayer with no server software that touches config.

**Comment by PuckiSilver** [comment]
Then it could very well be the mods, there I nothing in the pack that should ever reset the config unless you apply a preset or remove the objective it’s stored in, so not by itself.

I will close this for now but if you find out more information or can replicate it in a reliable way, please let me know and I will see what I can do.
