### ISSUE TITLE
How do i change the datapacks settings?

### ISSUE THREAD

**Issue by ISE9218** [ps-dps/MobCaptains#38]
ik i have to use the scoreboard but idk how to do it.

**Comment by PuckiSilver** [comment]
You can just type `/function ps-mob:config` and a menu should appear in your chat

**Comment by ISE9218** [comment]
> You can just type `/function ps-mob:config` and a menu should appear in your chat

yeah but what do i do to edit the values?

**Comment by PuckiSilver** [comment]
You can click on the text in chat, then it pastes a command into your text field. There you only need to type the value to which you want to set it and press return.

Then it changes the setting.

**Comment by ISE9218** [comment]
> You can click on the text in chat, then it pastes a command into your text field. There you only need to type the value to which you want to set it and press return.
> 
> Then it changes the setting.

oh i see. How can i change the settings back to the default?

**Comment by PuckiSilver** [comment]
You can run `/function ps-mob:_/config/default`

**Comment by ISE9218** [comment]
> You can run `/function ps-mob:_/config/default`

doesn't change the values

**Comment by PuckiSilver** [comment]
The default config will set it to these values
```json
     {
            ".cool_down":         60,
            ".spawn_chance":      10,
            ".notify_on_spawn":   2,
            ".notify_with_sound": 1,
            ".should_glow":       0,
            ".beam_on_spawn":     1,
            ".block_area":        12000,
            ".exists_for":        6000,

            ".weight_common":     50,
            ".weight_uncommon":   30,
            ".weight_rare":       9,
            ".weight_legendary":  2,
        }
```
This is copied directly from code.

Instead of constantly poking in the dark back and forth - what do you want to achieve exactly? What setting do you want to change? Can you explain your problem more broadly?

**Comment by ISE9218** [comment]
> The default config will set it to these values
> 
> ```json
>      {
>             ".cool_down":         60,
>             ".spawn_chance":      10,
>             ".notify_on_spawn":   2,
>             ".notify_with_sound": 1,
>             ".should_glow":       0,
>             ".beam_on_spawn":     1,
>             ".block_area":        12000,
>             ".exists_for":        6000,
> 
>             ".weight_common":     50,
>             ".weight_uncommon":   30,
>             ".weight_rare":       9,
>             ".weight_legendary":  2,
>         }
> ```
> 
> This is copied directly from code.
> 
> Instead of constantly poking in the dark back and forth - what do you want to achieve exactly? What setting do you want to change? Can you explain your problem more broadly?

i want the mobs to glow and notify of every rarity

**Comment by PuckiSilver** [comment]
The run these 2 commands in chat:
```mcfunction
scoreboard players set .should_glow config_score 1
scoreboard players set .notify_on_spawn config_score 4
```
