### ISSUE TITLE
How to remove the condition of captain mobs ?

### ISSUE THREAD

**Issue by maihuychuong** [ps-dps/MobCaptains#39]
Hello. So i want to farm drops from captian mobs in a mob farm. Can you show me how? Pls

**Comment by PuckiSilver** [comment]
Run this command:
`scoreboard players set .block_area ps-mob.config 0`
This will completely disable the feature that blocks mob captain spawns within the same area so mob farms should work again.

**Comment by maihuychuong** [comment]
I mean how to disable the condition. Mob captain need to be killed by a player.

**Comment by PuckiSilver** [comment]
For that you just need to remove the `"conditions"` key with its value in all the loot tables located at `data/ps-mob/loot_tables/captain/`

**Comment by maihuychuong** [comment]
Oh ok. Tks for ur hlep.
