### ISSUE TITLE
Removed scoreboard

### ISSUE THREAD

**Issue by cloodstool** [ps-dps/MobCaptains#46]
Hi, I tried configuring the mod through the scoreboard system, and I _think_ I managed to make the changes I wanted.

The thing is, this is my first time using the scoreboard system, and didn't really understand the instructions on the mod page initially. This led me to display the scoreboard on my sidebar before I realized I had to click on the options in the chat. When I made my changes, I thought the `/scoreboard objectives remove ps-mob.config` would hide the sidebar, but I think it removed the config file entirely.

Is this the case, or am I worrying for nothing? And if it is in fact gone, how do I revert this?

**Comment by PuckiSilver** [comment]
Yes, this did remove the config - but every time you rejoin the world (or restart the server), the config gets regenerated.
So just rejoin the single player world/restart the server and then redo your configuration.
If it ever happens again, you can remove a scoreboard from being displayed on the sidebar by running `scoreboard objectives setdisplay sidebar` without specifying a scoreboard after that.
Sorry for the inconvenience, hope this helps!

**Comment by cloodstool** [comment]
Got it, thanks for the clarification!
