### ISSUE TITLE
Mod and datapack?  Mod OR datapack?

### ISSUE THREAD

**Issue by allanonmage** [ps-dps/MobCaptains#6]
There is no how-to, and the modrinth page has a mod and a datapack available for download, yet the URL has datapack in it.

Which one gets installed?  Is there an option, or does it require both?

**Comment by PuckiSilver** [comment]
Hey,

you can install either the data pack version **or** the mod version, it doesn’t matter.
They are the same and function the same, they just come with the down and upsides of either.

Sorry to cause confusion
~PuckiSilver

**Comment by allanonmage** [comment]
I'm putting together a modpack for my server and this seems like a good fit, but I'm not familiar with the upsides and downsides of datapack vs mod.  The only difference I'm aware of is that a datapack is per world and a mod is for any world in that instance, which is moot because my server will only run the 1 world.

**Comment by PuckiSilver** [comment]
In your case, it probably doesn’t matter then, you can just pick whatever you like best
