### ISSUE TITLE
How do you convert Datapacks into Mods?

### ISSUE THREAD

**Issue by Simiea** [ps-dps/MobCaptains#7]
I would really appreciate it if you could tell me how your datapacks are being turned into mods. Not an issue but something I am curious about

**Comment by PuckiSilver** [comment]
Hey,

bellow the surface, they are the same, so even the mods still only use functions and other data pack features.

Modrinth provides this functionality directly on their site, [here](https://github.com/modrinth/knossos/blob/master/helpers/package.js) is the code from their website

Hope that helps
~PuckiSilver
